services:
  - type: web
    name: green-a
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_API_KEY
        sync: false
